version: '3.8'

services:
  postgres_main:
    image: postgres:15
    container_name: postgres_main_dev
    environment:
      POSTGRES_USER: root        # Choose consistent credentials
      POSTGRES_PASSWORD: root
      POSTGRES_DB: url_shortener_db # Consolidated DB name
    ports:
      - "5432:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis_dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq_dev
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    restart: unless-stopped

volumes:
  postgres_main_data:
  redis_data:
  rabbitmq_data: